# Generated by Django 5.0 on 2024-01-10 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/images/')),
                ('name', models.CharField(default='blog_image', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='blogs/covers/')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('image_list', models.ManyToManyField(to='app.blogimage')),
            ],
        ),
    ]
