# Generated by Django 5.0 on 2024-01-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='card_cover_image',
            field=models.ImageField(default='package/covers/bg.jpg', help_text="Image size should be 700 X 460. Click <a href='https://www.iloveimg.com/resize-image' style='color:lightblue'>here</a> to resize an image.", upload_to='package/covers/'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(default='package/images/bg.jpg', upload_to='package/images/'),
        ),
    ]
