# Generated by Django 5.0 on 2024-02-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_gallaryimage_query'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GallaryImage',
            new_name='GalleryImage',
        ),
    ]
