# Generated by Django 5.0 on 2023-12-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('destination', models.TextField(max_length=100)),
                ('adult_count', models.IntegerField()),
                ('child_count', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('admin_remark', models.TextField(max_length=200)),
            ],
        ),
    ]
