# Generated by Django 5.0 on 2023-12-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_indexquery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexQuery',
            new_name='QueryForm',
        ),
    ]
