# Generated by Django 5.0 on 2023-12-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_indexquery_queryform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryForm',
            new_name='Query',
        ),
    ]
