# Generated by Django 5.0 on 2023-12-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_destination_description_destination_map_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='dropof_location',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='night',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='pickup_location',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
