# Generated by Django 5.0 on 2023-12-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='admin_remark',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
