# Generated by Django 5.0 on 2023-12-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_contact_admin_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adult_count', models.IntegerField()),
                ('child_count', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
