# Generated by Django 5.0 on 2023-12-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_review_email_alter_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_remark',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
