# Generated by Django 5.0 on 2023-12-31 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_review_admin_remark_review_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='exclude',
            new_name='price_excludes',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='inclusion',
            new_name='price_includes',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='price_double_sharing',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='price_quad_sharing',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='price_triple_sharing',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='costing',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='iternary',
            field=models.JSONField(null=True),
        ),
    ]
